// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UserSegmentation.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SegmentAssignmentFeature : object, Xunit.IClassFixture<SegmentAssignmentFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SegmentAssignment.feature"
#line hidden
        
        public SegmentAssignmentFeature(SegmentAssignmentFeature.FixtureData fixtureData, UserSegmentation_AcceptanceTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "SegmentAssignment", "When a user\'s financials are updated, he will be automatically assigned to a segm" +
                    "ent", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="User will be assigned to segment after he updates his financials")]
        [Xunit.TraitAttribute("FeatureTitle", "SegmentAssignment")]
        [Xunit.TraitAttribute("Description", "User will be assigned to segment after he updates his financials")]
        [Xunit.InlineDataAttribute("1980-01-01", "29000", "80", "Default", new string[0])]
        [Xunit.InlineDataAttribute("1980-01-01", "34000", "80", "Default", new string[0])]
        [Xunit.InlineDataAttribute("2006-01-01", "34000", "80", "Default", new string[0])]
        [Xunit.InlineDataAttribute("1980-01-01", "34000", "90", "Silver", new string[0])]
        [Xunit.InlineDataAttribute("1980-01-01", "64000", "100", "Gold", new string[0])]
        public void UserWillBeAssignedToSegmentAfterHeUpdatesHisFinancials(string birthdate, string grossAnnualRevenue, string socialScore, string segment, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Birthdate", birthdate);
            argumentsOfScenario.Add("GrossAnnualRevenue", grossAnnualRevenue);
            argumentsOfScenario.Add("SocialScore", socialScore);
            argumentsOfScenario.Add("Segment", segment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User will be assigned to segment after he updates his financials", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
        testRunner.Given(string.Format("an existing user born on {0}", birthdate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
        testRunner.When(string.Format("he update his financials including {0} and {1}", grossAnnualRevenue, socialScore), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
        testRunner.Then(string.Format("he should be assigned to a {0}", segment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SegmentAssignmentFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SegmentAssignmentFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
