name: Build and deploy
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: dotnet test --verbosity normal
  
  deploy-docs:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Deploy docs to Notion
        run: node notion_integration.js
    env:
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      NOTION_SECRET: ${{ secrets.NOTION_AUTH }}
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Generate Kubeconfig
        run: |
          echo ${{ secrets.KUBECONFIG }} > k8s/config

      - name: Deploy
        run: |
          kubectl --kubeconfig=k8s/config apply -f k8s/

      - name: Clean-Up
        run: |
          rm k8s/config
