name: Build and deploy
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
          
  deploy-docs:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Deploy docs to Notion
        run: node notion_integration.js
    env:
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
      NOTION_SECRET: ${{ secrets.NOTION_AUTH }}
      
  deploy:
    runs-on: self-hosted
    steps:
    #    - name: Generate Kubeconfig and Certs
    #      run: |
    #        echo ${{ secrets.KUBECONFIG }} > k8s/config

      - name: Kubernetes Deployment
        run: |
          cd k8s
          kubectl apply -f .

#    - name: Clean-Up
#      run: |
#        rm path/to/deploy.kubeconfig
#        rm path/to/cert
